// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpstreamDbSettings_MoreClientProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpstreamDbSettings_MoreClientProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201305211454564_UpstreamDbSettings_MoreClientProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
