// <auto-generated />
namespace JabbR.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpstreamExtendChatUserFlagLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpstreamExtendChatUserFlagLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201307031047292_UpstreamExtendChatUserFlagLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
